####
# This Dockerfile is used in order to build a container that runs the spring application in native (no JVM) mode.
# It uses a micro base image, tuned for spring native executables.
# It reduces the size of the resulting container image.
# Check https://quarkus.io/guides/quarkus-runtime-base-image for further information about this image.
FROM quay.io/quarkus/ubi9-quarkus-micro-image:2.0
WORKDIR /app
ADD target/spring-boot-docker ./
EXPOSE 8080
ENTRYPOINT ["./spring-boot-docker"]